// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBbo8QUCocyqon0INo_ZYIi26P3MJf1h4',
    appId: '1:904492789891:web:0f7c33543e1ee785976bb6',
    messagingSenderId: '904492789891',
    projectId: 'uywa-be7a9',
    authDomain: 'uywa-be7a9.firebaseapp.com',
    storageBucket: 'uywa-be7a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyYU81WW4ocgbHv2AN2mBxLmeHC9jNO3o',
    appId: '1:904492789891:android:17d3aa23ee0d32d7976bb6',
    messagingSenderId: '904492789891',
    projectId: 'uywa-be7a9',
    storageBucket: 'uywa-be7a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2GIgmK0gI9MYiO_M1uQsXMBkWqc0oia4',
    appId: '1:904492789891:ios:48870be0101d367c976bb6',
    messagingSenderId: '904492789891',
    projectId: 'uywa-be7a9',
    storageBucket: 'uywa-be7a9.firebasestorage.app',
    iosBundleId: 'com.example.mypets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2GIgmK0gI9MYiO_M1uQsXMBkWqc0oia4',
    appId: '1:904492789891:ios:48870be0101d367c976bb6',
    messagingSenderId: '904492789891',
    projectId: 'uywa-be7a9',
    storageBucket: 'uywa-be7a9.firebasestorage.app',
    iosBundleId: 'com.example.mypets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBbo8QUCocyqon0INo_ZYIi26P3MJf1h4',
    appId: '1:904492789891:web:22d37170a313fb23976bb6',
    messagingSenderId: '904492789891',
    projectId: 'uywa-be7a9',
    authDomain: 'uywa-be7a9.firebaseapp.com',
    storageBucket: 'uywa-be7a9.firebasestorage.app',
  );
}
